on: 
  push:
    branches:
      - main
name: 🚀 Push File

jobs:
  copy-file:
    name: 🎉 Checkout
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'Imagens'
        destination_repo: 'RafaelReis891/Web_Models'
        destination_folder: 'Web_Models'
        user_email: 'geraldorafaelreis@gmail.com'
        user_name: 'RafaelReis891'
        commit_message: 'A custom message for the commit'
